// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <esp_lvgl_port.h>

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);

extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Container1;

void ui_event_Dropdown1(lv_event_t *e);

extern lv_obj_t *ui_Dropdown1;

void ui_event_Button1(lv_event_t *e);

extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label2;

void ui_event_TextArea2(lv_event_t *e);

extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label5;

void ui_event_Keyboard1(lv_event_t *e);

extern lv_obj_t *ui_Keyboard1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_anime_480x480_png); // assets/anime_480x480.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
